import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { GetStaticProps } from 'next';


type props = {
  prayerTimes: {
    [prayer: string]: string;
  };
};




 export default function index({ prayerTimes }: props) {

  
  return (
   


    <div className='absolute top-0 h-screen w-full max-w-full flex flex-col items-center '>

    <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
    </Head>
 <div className=' flex flex-row my-6 w-full h-16 items-center justify-evenly'>
 <Link href='/Syria'> <button className='h-6 w-11 bg-black'>Syr</button></Link>
 <Link href='/Turkey'> <button className='h-6 w-11 bg-black'>Tr</button></Link>
 <Link href='/De'> <button className='h-6 w-11 bg-black'>De</button></Link>
 <Link href='/Jordan'> <button className='h-6 w-11 bg-black'>jo</button></Link>
 <Link href='/Sudi'> <button className='h-6 w-11 bg-black'>Su</button></Link>
 <Link href='/Egypt'> <button className='h-6 w-11 bg-black'>Eg</button></Link>

 </div>

 <div className='w-[20rem] h-[29rem] rounded-2xl backdrop-brightness-50 flex flex-col justify-center items-center my-[4.5rem]  '>
   <div className=''>
   <Image src='/quran.png' alt="quran-deaa" width={250} height={250}   />
   </div>
   
   <div className='flex justify-center items-center flex-col'>
   <h1 className='text-right'>بسم الله الرحمن الرحيم</h1>
   <p className='text-right mx-3'>اهلا وسهلا بكم أخواني و أخواتي في الأمساكية الألكتروني ، اختر  البلد الذي تقيم به من الآعلى لعرض لك الأمساكية الخاصة بالبلد المقيم به</p>
   </div>
 </div>
    
 
   
      


    </div>
    );
};




export  const getStaticProps: GetStaticProps<props> = async () => {
  const [res, res1] = await Promise.all([
    fetch("https://muslimsalat.com/germany/monthly/24-03-2023/true.json?key=705ad57b02ad96ff58f3ca25bc911a6b"),
    fetch("https://muslimsalat.com/germany/monthly/01-04-2023/true.json?key=705ad57b02ad96ff58f3ca25bc911a6b"),
  ]);

  const data = {
    prayerTimes: [...(await res.json()).items, ...(await res1.json()).items],
  };
console.log(data);

  return {
    props: data,
    revalidate: 3600, 
  };
}
